-- 为 stars 表添加生涯荣誉字段
ALTER TABLE stars ADD COLUMN IF NOT EXISTS all_nba INTEGER DEFAULT 0;
ALTER TABLE stars ADD COLUMN IF NOT EXISTS all_defense INTEGER DEFAULT 0;
ALTER TABLE stars ADD COLUMN IF NOT EXISTS mvp INTEGER DEFAULT 0;
ALTER TABLE stars ADD COLUMN IF NOT EXISTS fmvp INTEGER DEFAULT 0;
ALTER TABLE stars ADD COLUMN IF NOT EXISTS championships INTEGER DEFAULT 0;
ALTER TABLE stars ADD COLUMN IF NOT EXISTS all_star INTEGER DEFAULT 0;

-- 为 user_stars 表添加自定义头像字段
ALTER TABLE user_stars ADD COLUMN IF NOT EXISTS custom_avatar VARCHAR(255);

-- 为 user_stars 表添加自定义荣誉字段
ALTER TABLE user_stars ADD COLUMN IF NOT EXISTS all_nba INTEGER;
ALTER TABLE user_stars ADD COLUMN IF NOT EXISTS all_defense INTEGER;
ALTER TABLE user_stars ADD COLUMN IF NOT EXISTS mvp INTEGER;
ALTER TABLE user_stars ADD COLUMN IF NOT EXISTS fmvp INTEGER;
ALTER TABLE user_stars ADD COLUMN IF NOT EXISTS championships INTEGER;
ALTER TABLE user_stars ADD COLUMN IF NOT EXISTS all_star INTEGER;
